### PR TITLE
Add Apillon NCTR token

### PR DESCRIPTION
**Pull request by MoMannn**
## Signature Auto check (For `asset` category)

Asset Owner & Signature Account:
`169a2i3nCNGv9dscdvy61xEgfDU3595ynWJn4xKyaTR8oB1F` (one of the signers of the asset multisig owner)

Data that needs to be signed:
`file`

Signature Hash: `0x7cfb43a3dbb8c41885ed6fcfcd42eabad98b45c70b968fc0ac2b07512ed3412daec33ea430bb78262f0fb29ee263fdc8c2345f0c534daddb2fa9ca2047775509`

## Verification (For `asset` category)

Your Identity:
`Apillon CTO`

### CODE REVIEW

**Comment by carlhong** [comment]
image
Verify failed.

**Comment by MoMannn** [comment]
That seems to be some kind of a bug. Or a problem with the new polkadot ledger app because I cannot verify my own signature either:

https://www.loom.com/share/7977a8f4a08c4602b4f112ace3cdf773?sid=10dcaae4-bfa9-45d2-8ca0-9a7bc608788d

So I rather created a hash of the string via:

https://www.md5hashgenerator.com/
sha1:  f9a615c0b5438ae9e835c0c63677120fde3b8735

Which gives the signature: 
0x1fde12c56f1b01d3a0cbcf6ede50c26e658716c63692444fc4ab031f69e564dd73cc469113eedac62c98611fa7e7142fd5f151360433c7c5bf2d7cca6f63bc0b

That should work.

**Comment by MoMannn** [comment]
Its the enter in the end. My input is from ctrl + a, ctrl + c from the file so its:

``` 
{
  "TokenID": "1024",
  "TokenSymbol": "NCTR",
  "Logo": "../logos/assethub-polkadot_asset_NCTR.png",
  "Description (en)": "Apillon - Blockchain simplified. Innovation amplified. Apillon streamlines blockchain development, making it easy for web2 developers to build decentralized applications without delving into the complexities of blockchains or managing multiple tokens. With nearly 150k developers and an average daily influx of 800, manage and create your dApps effortlessly using our intuitive UI/CLI or seamless REST API integration.",
  "Description (zh)": "Apillon - 区块链简化。创新得到放大。Apillon 简化了区块链开发，使 web2 开发人员可以轻松构建去中心化应用程序，而无需深入研究区块链的复杂性或管理多个代币。拥有近 15 万名开发人员，平均每天有 800 名开发人员涌入，使用我们直观的 UI/CLI 或无缝 REST API 集成，轻松管理和创建您的 dApp.",
  "Website Link": "https://apillon.io/",
  "Twitter Link": "https://x.com/Apillon",
  "Telegram Link": "https://t.me/Apillon/1",
  "Discord Link": "https://discord.gg/sYkR7BPF",
  "Medium Link": "https://medium.com/@apillon",
  "Github Link": "https://github.com/Apillon",
  "Category": "asset",
  "Network": "assethub-polkadot"
}

```

**Comment by carlhong** [comment]
image

Verified!

**Review by carlhong — APPROVED** [review]

**Pull request merged**
