### PR TITLE
add acala tdot

### PR DESCRIPTION
**Pull request by ukby1234**
## Signature Auto check (For `asset` category)

Asset Owner & Signature Account:
`tEb1xUcts6LghHUrG2KeygtxQJtF8AeznxMVBmJHF2LBeuz`

Data that needs to be signed:
`file`

Signature Hash: `0xd0407d3acc0bfbb849f588fbcb5556f2cbaec7743b8b6e31715138c6238aea0b5cf6ebb59e972245a8116c447a566adfed22c12a321e7671284c8c4898920a8e`

## Verification (For `system`|`custom`|`erc20`|`erc721` category)

Your Identity:
`Other`

### CODE REVIEW

**Comment by carlhong** [comment]
https://acala.subscan.io/custom_tokens

1. tDOT is in **custom** category
2. Logo File Name format: network_category_symbol.<png/svg> (e.g. acala-testnet_asset_ABC.png)
3. "TokenID" should be tDOT

**Comment by ukby1234** [comment]
@carlhong fixed naming and category.

**Comment by carlhong** [comment]
@ukby1234 
the correct format name should be as follow:
image
You may also upstream your repo to latest commit to make action verify work.

**Comment by ukby1234** [comment]
@carlhong fixed naming.

**Review by carlhong — APPROVED** [review]

**Pull request merged**
