### PR TITLE
Add xcTUR asset on Moonriver

### PR DESCRIPTION
**Pull request by imstar15**
## Signature Auto check (For `asset` category)

Asset Owner & Signature Account:
`0xfE66125343Aabda4A330DA667431eC1Acb7BbDA9`

Data that needs to be signed:
`file`

Signature Hash: `0x04eb3489296b6ae78d66b1fccfcfcfae7a58647c1dadec5011b8a07292a5a6f84eda6cb461d6f29fa67e115eaef3891369ecc25b23a74f346b4c14db6108513300`

## Verification (For `system`|`custom`|`erc20`|`erc721` category)

Your Identity:
`Team Member`

### CODE REVIEW

**Comment by chrisli30** [comment]
Hi Subscan team, Chris founder of OAK Network here. In this PR, the owner `0x6D6f646c617373746d6E67720000000000000000` is the XC20 token smart contract address, which was deployed by a Moonriver governance proposal. We have no access control of that address. Could I ask how could we pass the signature check for it?
image


Could we change it to my wallet address, `0xfE66125343Aabda4A330DA667431eC1Acb7BbDA9`? Then, I will be able to generate a signature hash with my wallet.

**Comment by carlhong** [comment]
@chrisli30 sure, in this case, you can use your wallet to sign, we'll verify manually for you.

**Comment by chrisli30** [comment]
@carlhong Thank you Carl 👌 

The provided signature hash is already signed from my wallet, `0xfE66125343Aabda4A330DA667431eC1Acb7BbDA9 `

CleanShot 2024-03-05 at 09 25 00

Could you double check it?

**Comment by carlhong** [comment]
image
Verified

**Review by carlhong — APPROVED** [review]

**Pull request merged**
