### PR TITLE
Add DBC DLC asset

### PR DESCRIPTION
**Pull request by kaigedong**
## Signature Auto check (For `asset` category)

Asset Owner & Signature Account:
`5HEqQBsJ9GCS1pGfU6hQByYBtHt5PuToGwpXqXDhkKJumLom`

Data that needs to be signed:
`file`

Signature Hash: `0x8ed5589cec17f59507660c74d18ec3701edde65589379411be9ab036195e1e20472cd93be074b275eceedab9f73161690cb22d340abb58d9fa4c3cb4872c4d86`

## Verification (For `system`|`custom`|`erc20`|`erc721` category)

Your Identity:
`Other`

### CODE REVIEW

**Comment by carlhong** [comment]
image
Signature is not verified.

**Comment by yakio** [comment]
The automatic verification program prompts that the signature has not been verified. The possible reason is that the content of the signature may not be completely copied. Please try to use the [Copy] button to copy the entire content and sign it, and modify it to the new signature in the pr description.
image

**Comment by kaigedong** [comment]
@carlhong @yakio Thank you very much for your help. I have modified the signature hash and now it works!
截图 2023-05-19 13-06-26

**Comment by carlhong** [comment]
image
Verified

**Review by carlhong — APPROVED** [review]

**Pull request merged**
