### PR TITLE
AssetX Token Subscan assets info

### PR DESCRIPTION
**Pull request by Steak-King**
## Signature Auto check (For `asset` category)

Asset Owner & Signature Account:
`14iULn6TYRmawsxazqR2xwWVuyDXc8ycGjg7ppJ15qVKctEN`

Data that needs to be signed:
`file`

Signature Hash: `0x50ee55058c2d05b12a8235db2846981215b987751d9c51c92c6dcd6352fedf6caad5db554add8e17a5fb45804d34e8ea7399a1e3900623281be4221ff4c64289`

## Verification (For `system`|`custom`|`erc20`|`erc721` category)

Your Identity:
`Founder CEO`

### CODE REVIEW

**Comment by Steak-King** [comment]
Hi, I can now see that the Logo file size was much bigger than allowed. But the Signature Hash is definitely correct.
Please let me know how I can fix this?

**Comment by carlhong** [comment]
The logo file size should be less than 30k, you can replace with a logo with lower resolution.

**Comment by Steak-King** [comment]
> The logo file size should be less than 30k, you can replace with a logo with lower resolution.

Logo has been updated. Is there anything else required from our side?

**Comment by carlhong** [comment]
> > The logo file size should be less than 30k, you can replace with a logo with lower resolution.
> 
> Logo has been updated. Is there anything else required from our side?

Take this [pr](https://github.com/subscan-explorer/assets-info/pull/30/files) as an example, you need to update the file name in the correct format as described in README.

**Pull request closed without merging**
