### PR TITLE
feat: add GameDAO GAME

### PR DESCRIPTION
**Pull request by 2075**
## Signature Auto check (For `asset` category)

Asset Owner & Signature Account:
`145njsry26hqqFUU2QeFc4vLQk8KQocC9thURdefviD3Dshz`

Data that needs to be signed:
`file`

Signature Hash: `0x6a0ed6d3c7148f24d12a269fe0054b15f0fcc711e41bbaf56e15a2fe9e48860a610d28ef76982d3d8cd4e9c10e2e1fb4f94ab8a117289642ce7cbb8b5876d288`

## Verification (For `system`|`custom`|`erc20`|`erc721` category)

Your Identity:
`Team Member`

### CODE REVIEW

**Comment by 2075** [comment]
hi! as far as understood, the string 'file' needs to be signed by the admin account, correct?

**Comment by 2075** [comment]
hey there, do you need any other information? the asset has also been registered on hydration and astar and it would be great to make it identifiable. cheers!

**Review by carlhong — APPROVED** [review]

**Comment by carlhong** [comment]
> hey there, do you need any other information? the asset has also been registered on hydration and astar and it would be great to make it identifiable. cheers!

@2075 you can pr to add token to hydration and astar.

**Comment by 2075** [comment]
> @2075 you can pr to add token to hydration and astar.

thanks @carlhong we have done it, only subscan was missing, thanks for merging.

**Review by chiamaka96 — COMMENTED** [review]
1hi

**Pull request merged**
