### PR TITLE
here comes le pepe

### PR DESCRIPTION
**Pull request by pepecoinksm**
## Signature Auto check (For `asset` category)

Asset Owner & Signature Account:
`D69PEPED6ix2BQy6Ux14fNqjKyz4MLzsGCLuoMwTMxzXi3f`

Data that needs to be signed:
`file`

Signature Hash: `0x0c47909dc7a01d0051c83a2aa92882be95125d166142fbcba05a77024cad2e263c338323940df842774d9f58af5de5cfd37af05d6bb938e6c0e3e6f98578d981`

## Verification (For `system`|`custom`|`erc20`|`erc721` category)

Your Identity:
`Team Member`

### CODE REVIEW

**Comment by carlhong** [comment]
Please refer to this [pr](https://github.com/subscan-explorer/assets-info/pull/18) and submit the corresponding file.

**Comment by pepecoinksm** [comment]
good now fren?

**Comment by pepecoinksm** [comment]
reeeee! wat am i doin wrong fren?

**Comment by carlhong** [comment]
1. The logo size should be less than 30KB
2. In this case: the file name should be statemine_asset_PEPE.png and statemine-asset-PEPE.json

Thanks for your submission. We appreciate your effort, but please note that it contains offensive and unfriendly words. We kindly request you to revise your document by removing any insulting or disrespectful words. Let's work together to maintain a positive and respectful environment.

**Comment by pepecoinksm** [comment]
okey okey fren, i did it! sry for the offensive language it was a bad joke, plz forgive fren

**Review by carlhong — APPROVED** [review]

**Review by DaddyG90 — COMMENTED** [review]
DaddyG90

**Pull request merged**
