### PR TITLE
ASNA Token

### PR DESCRIPTION
**Pull request by xXcoconut3Xx**
## Signature Auto check (For `asset` category)

Asset Owner & Signature Account:
`0x53328317dc82f64c172011F5206B72B75838Db72`

Data that needs to be signed:
`file`

Signature Hash: `0x7ca9a4412a072563112143c844cad8620a5bcf5e1356d033908b4439d6d62e18`

## Verification (For `system `erc20`)

Your Identity:
`Owner`

### CODE REVIEW

**Comment by carlhong** [comment]
The file name should be astar_erc20_ASNA.png and astar-erc20-ASNA.json.

**Comment by xXcoconut3Xx** [comment]
ok - how can i change this?

**Comment by xXcoconut3Xx** [comment]
can someone review this for merging?

**Comment by carlhong** [comment]
image
The file name should be astar-erc20-ASNA.json.

**Comment by xXcoconut3Xx** [comment]
> image
> The first file name should be astar-erc20-ASNA.json.

Done ;-)

**Comment by carlhong** [comment]
It is "astar-erc20-ASNA.json", not "astar_erc20_ASNA.json"

**Comment by xXcoconut3Xx** [comment]
can someone review this for merging?

**Review by carlhong — APPROVED** [review]

**Pull request merged**
