### PR TITLE
feat: add airlyft nft

### PR DESCRIPTION
**Pull request by rmagon**
## Signature Auto check (For `erc721` category)

Asset Owner & Signature Account:
`0x685aCfc099E2a0bc75Aa833949291Be794D31730`

Data that needs to be signed:
`file`

Signature Hash: `<REPLACE THE SIGNATURE>`

## Verification (For `erc721` category)

Your Identity:
`Team Member`

### CODE REVIEW

**Comment by rmagon** [comment]
Since the [readme says](https://github.com/subscan-explorer/assets-info#about-the-signature) that verification is required only for `asset` category, I'm guessing signature not required for `erc721`?

**Comment by rmagon** [comment]
Hi @carlhong, I have two small questions
1. This is an erc721 NFT, can i sign from my EVM wallet, will it work?
2. The logo is a png with less than 30KB file size, is there something still wrong?

Thank you in advance

**Comment by carlhong** [comment]
Hi, the logo file name needs to follow this format ( network_category_symbol.<png/svg> )
In this case, the name should be "astar_erc721_AIRLYFT2024.png"

**Comment by rmagon** [comment]
Hi @carlhong. Thank you for your help in getting the checks to pass. Really appreciate it.

**Review by Emisio1 — APPROVED** [review]

**Review by carlhong — APPROVED** [review]

**Pull request merged**
